'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useUser } from '@/context/UserContext';
import { collectionsApi } from '@/lib/collections';
import { quizApi } from '@/lib/quiz';
import type { Collection } from '@/types';

export default function QuizPage() {
  const { userId } = useUser();
  const router = useRouter();
  const [collections, setCollections] = useState<Collection[]>([]);
  const [collectionId, setCollectionId] = useState('');
  const [numQuestions, setNumQuestions] = useState(5);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    collectionsApi.list(userId).then(setCollections).catch(() => {});
  }, [userId]);

  async function startQuiz() {
    setLoading(true);
    setError('');
    try {
      const session = await quizApi.start(userId, numQuestions, undefined, collectionId || undefined);
      router.push(`/quiz/${session.sessionId}`);
    } catch {
      setError('Could not start quiz. Make sure the backend is running and you have uploaded documents.');
      setLoading(false);
    }
  }

  return (
    <div style={{ maxWidth: '560px' }}>
      <div style={{ fontSize: '9px', letterSpacing: '0.24em', textTransform: 'uppercase', color: 'var(--mercury-accent)', marginBottom: '6px' }}>
        LLM-Graded
      </div>
      <h1 style={{ fontFamily: 'var(--font-cinzel), Cinzel, serif', fontSize: '26px', fontWeight: 600, letterSpacing: '0.04em', color: 'var(--foreground)', marginBottom: '36px' }}>
        Quiz
      </h1>

      {/* Number of questions */}
      <div style={{ marginBottom: '28px' }}>
        <label style={{ display: 'block', fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--text-muted-col)', marginBottom: '10px' }}>
          Questions — <span style={{ color: 'var(--mercury-accent)' }}>{numQuestions}</span>
        </label>
        <input
          type="range"
          min={3} max={15} value={numQuestions}
          onChange={e => setNumQuestions(+e.target.value)}
          style={{ width: '100%', accentColor: 'var(--mercury-accent)', cursor: 'pointer' }}
        />
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '9px', color: 'var(--text-subtle)', marginTop: '4px' }}>
          <span>3 min</span><span>15 max</span>
        </div>
      </div>

      {/* Collection filter */}
      {collections.length > 0 && (
        <div style={{ marginBottom: '28px' }}>
          <label style={{ display: 'block', fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--text-muted-col)', marginBottom: '10px' }}>
            Source
          </label>
          <select
            value={collectionId}
            onChange={e => setCollectionId(e.target.value)}
            style={{
              width: '100%', background: 'var(--card)', border: '1px solid #1c1912',
              color: 'var(--foreground)', padding: '10px 14px', fontSize: '13px',
              fontFamily: 'inherit', outline: 'none', cursor: 'pointer', borderRadius: '2px',
            }}
          >
            <option value="">All documents</option>
            {collections.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
        </div>
      )}

      {error && <p style={{ fontSize: '11px', color: 'var(--error)', marginBottom: '16px' }}>{error}</p>}

      <button
        onClick={startQuiz}
        disabled={loading}
        style={{
          padding: '12px 32px',
          border: '1px solid var(--mercury-accent)',
          color: 'var(--mercury-accent)',
          background: loading ? 'var(--accent-dim)' : 'transparent',
          fontSize: '11px', letterSpacing: '0.08em', textTransform: 'uppercase',
          fontFamily: 'inherit', cursor: loading ? 'wait' : 'pointer',
          opacity: loading ? 0.7 : 1, transition: 'all 0.2s', borderRadius: '2px',
        }}
      >
        {loading ? 'Generating questions...' : 'Start Quiz →'}
      </button>

      <p style={{ fontSize: '10.5px', color: 'var(--text-subtle)', marginTop: '14px', lineHeight: 1.7 }}>
        Questions are generated by Cohere Command-R from your uploaded documents. This takes a few seconds.
      </p>
    </div>
  );
}
